Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.hostname = "rocky9-cli"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.synced_folder ENV['ROCKY_CACHE_DIR'] || "../cache", "/vagrant/cache",
    create: true, type: "rsync", rsync__auto: false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
    # Disk size handled by vagrant-disksize plugin
  end
  config.vm.provider "hyperv" do |hv|
    hv.memory = 4096
    hv.cpus = 2
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = { cache_dir: "/vagrant/cache" }
  end
  # Add disk resizing via vagrant-disksize plugin if present
  # Minimum recommended disk size for CLI VM is 150GB
  if Vagrant.has_plugin?("vagrant-disksize")
    config.disksize.size = '150GB'
  end
end
