- name: Rocky 9 CLI + Apache Tomcat
  hosts: all
  become: true
  tasks:
    - name: Ensure dnf plugins and update cache
      dnf:
        name:
          - dnf-plugins-core
        state: present

    - name: Refresh DNF metadata
      command: dnf makecache
      changed_when: false

    - name: List available groups (for debug)
      command: dnf group list
      register: group_list
      changed_when: false

    - name: Ensure minimal system (remove unwanted packages)
      dnf:
        name: "@core"
        state: present

    - name: Remove extra packages (no GUI groups)
      dnf:
        name:
          - "@workstation"
          - "@graphical-admin-tools"
          - "@multimedia"
          - "@office-suite"
        state: absent
        skip_broken: yes

    - name: Remove old Python versions
      dnf:
        name:
          - python2
          - python36
          - python38
        state: absent
        skip_broken: yes

    - name: Install latest Python 3 and pip
      dnf:
        name:
          - python3
          - python3-pip
        state: latest

    - name: Install Java (required for Tomcat)
      dnf:
        name: java-11-openjdk
        state: present

    - name: Install Tomcat
      dnf:
        name: tomcat
        state: present

    - name: Ensure Tomcat is started and enabled
      systemd:
        name: tomcat
        state: started
        enabled: yes

    - name: Gather final facts for report
      setup:
      register: final_facts

    - name: Ensure reports directory exists on host
      file:
        path: /vagrant/../reports
        state: directory
        mode: '0777'

    - name: Write HTML report with VM facts
      copy:
        dest: /vagrant/../reports/vm_report_tomcat.html
        content: |
          <html>
          <head><title>Tomcat VM State Report</title></head>
          <body>
          <h1>Tomcat VM State Report</h1>
          <h2>All Ansible Facts</h2>
          <pre>{{ final_facts.ansible_facts | to_nice_json }}</pre>
          </body>
          </html>
